/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type JsonSchema struct {
	Id string `json:"id"`
	Models *interface{} `json:"models"`
	Properties *interface{} `json:"properties"`
	Required []string `json:"required"`
}
