/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainForwardingMask struct {
	// Displays at the top of the browser window and in search results.
	Title string `json:"title,omitempty"`
	// A short description of your website to display in search engine results.
	Description string `json:"description,omitempty"`
	// A list of comma-separated keywords that describes the content and purpose of your website.
	Keywords string `json:"keywords,omitempty"`
}
