/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DomainSuggestion struct {
	// Suggested domain name
	Domain string `json:"domain"`
}
